### ISSUE TITLE
Feature Request: unlock all areas

### ISSUE THREAD

**Issue by strikersix23** [mateusz-korbut/GTA-DE-Cheat-Menu#1]
Any chance to add the option to unlock all cities?

**Comment by mateusz-korbut** [comment]
If I recall correctly, it's done by mission, so there's no way to do it programmatically besides running/completing the mission, which could break the game.

Also, I don't see anything regarding islands/cities in CLEO scripts - https://library.sannybuilder.com/#/sa_unreal/script/classes

**Comment by strikersix23** [comment]
I once decompiled and privately posted and android script that did similar to what I'm requesting it involves OBJECT GROUP BARRIERS1 AND BARRIERS2 i had requested permission to share the script from the author but got no response this was in cleo how ever based of the code itself it just fakes the mission check and removes the barriers

**Comment by mateusz-korbut** [comment]
I've found [thread](https://gtaforums.com/topic/837030-gta-sa-how-to-unlock-the-sf-and-lv-in-the-beginning-with-mainscm-scri/#findComment-1068362458) about it. It removes barriers, and you can go through bridges, but I'm not sure if that is what you wish for. I can also add editing statistics, which will unlock islands, but they will break the main storyline.

**Comment by strikersix23** [comment]
Thars whar I wish for In sa
